spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mintchat
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: IzU6W6TIxxQNPXAsWnqxSeVcZn7jkc5NpsDqZz0dqwt
  expiration: 86400000